#!/usr/bin/env python

import sys
import json

with open(sys.argv[1], 'r') as f:
    the_model = json.load(f)

interaction_model = the_model.get("interactionModel")
language_model = interaction_model.get("languageModel")
#print("%s" % language_model)

types = language_model.get("types")
#print("%s" % types)
for type in types:
	print("type %s\n" % (type.get("name")))
	type_name = type.get("name")
	type_values = type.get("values") 
	print("### %s Slot " % (type_name))
	print("\n")
	print("| What you can say | lircdo server meta Key & Value |\n")
	for value in values:
		type_value_id = value.get("id")
		type_value_name = value.get("name")
		type_value_name_value = type_value_name.get("value")
		type_value_name_synonyms = type_value_name.get("synonyms", [])
		print('| %s' % (type_value_name_value))
		if (len(type_value_name_synonyms) > 0):
			for synonym in type_value_name_synonyms:
				print(",%s" % (synonym))
			print("| %s |\n" % (type_value_id))
		print("\n")
